# =============================================================================
# SCRIPT 04 -- Predict Match Scores
# =============================================================================
# WHAT THIS SCRIPT DOES:
#   Loads the team ratings from Script 03 and generates score predictions
#   for any fixtures you ask it about.
#
#   Run it in two modes:
#
#   MODE 1 -- Predict specific matches (list them in FIXTURES below)
#     python3 src/04_predict_matches.py
#
#   MODE 2 -- Predict ALL possible current-season fixtures
#     python3 src/04_predict_matches.py --all
#
# WHAT YOU'LL GET:
#   outputs/predictions.csv  -- predicted scorelines + probabilities
#   A formatted summary printed to the terminal
# =============================================================================

import pandas as pd
import numpy as np
from scipy.stats import poisson
import json
import os
import sys
from datetime import date


# --- CONFIGURATION -----------------------------------------------------------

OUTPUTS_FOLDER = "outputs"

# ---- EDIT THIS SECTION TO ADD YOUR FIXTURES ---------------------------------
#
# Add the matches you want to predict here.
# Format: ("Home Team", "Away Team", "Date")
# Date is optional -- use "" if you don't know it yet.
# Team names must match exactly what's in your ratings file.
# Tip: check outputs/team_ratings.csv for the exact spelling.
#
FIXTURES = [
    # Matchweek 29 -- 14-16 March 2026
    ("Sunderland",    "Brighton",       "2026-03-14"),
    ("Burnley",       "Bournemouth",    "2026-03-14"),
    ("Chelsea",       "Newcastle",      "2026-03-14"),
    ("Arsenal",       "Everton",        "2026-03-14"),
    ("West Ham",      "Man City",       "2026-03-14"),
    ("Nott'm Forest", "Fulham",         "2026-03-15"),
    ("Man United",    "Aston Villa",    "2026-03-15"),
    ("Crystal Palace","Leeds",          "2026-03-15"),
    ("Liverpool",     "Tottenham",      "2026-03-15"),
    ("Brentford",     "Wolves",         "2026-03-16"),
]
# -----------------------------------------------------------------------------

MAX_GOALS = 9  # score matrix runs from 0 to MAX_GOALS-1


# --- LOAD RATINGS ------------------------------------------------------------

def load_ratings_and_params():
    """
    Loads team ratings (from Script 03) and model parameters.
    Returns a ratings lookup dict and the model params.
    """
    ratings_path = OUTPUTS_FOLDER + "/team_ratings.csv"
    params_path  = OUTPUTS_FOLDER + "/model_params.json"

    if not os.path.exists(ratings_path):
        raise Exception("team_ratings.csv not found. Run Script 03 first.")
    if not os.path.exists(params_path):
        raise Exception("model_params.json not found. Run Script 03 first.")

    ratings = pd.read_csv(ratings_path)
    with open(params_path) as f:
        params = json.load(f)

    # Validate the CSV has the expected columns.
    # If columns are missing it usually means team_ratings.csv was generated
    # by an older version of Script 03 -- fix by re-running Script 03.
    required_cols = ["Team", "Attack", "Defence", "Current"]
    missing_cols  = [c for c in required_cols if c not in ratings.columns]
    if missing_cols:
        raise Exception(
            "team_ratings.csv is missing columns: " + str(missing_cols) + "\n"
            "  This usually means it was generated by an older version of Script 03.\n"
            "  Fix: re-run Script 03 to regenerate it:\n"
            "    python3 src/03_train_ratings.py"
        )

    # Build a fast lookup: team name -> {Attack, Defence}
    lookup = {}
    for _, row in ratings.iterrows():
        lookup[row["Team"]] = {
            "Attack":  row["Attack"],
            "Defence": row["Defence"],
            "Current": row["Current"],
        }

    return lookup, params


# --- PREDICTION ENGINE -------------------------------------------------------

def predict_match(home, away, lookup, home_adv, rho):
    """
    Predicts the outcome of a single match using the Dixon-Coles model.

    Steps:
    1. Calculate expected goals for each team
    2. Build a score probability matrix using Poisson distributions
    3. Apply Dixon-Coles low-score correction
    4. Sum up win/draw/loss probabilities and find most likely scorelines

    Returns a dict with all prediction outputs.
    """
    if home not in lookup:
        raise ValueError("Unknown team: '" + home +
                         "'. Check spelling against team_ratings.csv")
    if away not in lookup:
        raise ValueError("Unknown team: '" + away +
                         "'. Check spelling against team_ratings.csv")

    # Expected goals for each team
    # mu_h = exp(home_attack + away_defence + home_advantage)
    # mu_a = exp(away_attack + home_defence)
    # Note: defence parameter is on log scale -- higher = concedes more
    mu_h = np.exp(
        lookup[home]["Attack"] + lookup[away]["Defence"] + home_adv
    )
    mu_a = np.exp(
        lookup[away]["Attack"] + lookup[home]["Defence"]
    )

    # Build score probability matrix
    # matrix[h, a] = probability that home scores h and away scores a
    matrix = np.zeros((MAX_GOALS, MAX_GOALS))

    for hg in range(MAX_GOALS):
        for ag in range(MAX_GOALS):
            # Joint probability: P(home=hg) * P(away=ag)
            # Poisson.pmf(k, mu) = probability of exactly k goals given rate mu
            p = poisson.pmf(hg, mu_h) * poisson.pmf(ag, mu_a)

            # Dixon-Coles correction for 0-0, 1-0, 0-1, 1-1
            # Adjusts for Poisson's tendency to undercount draws
            if   hg == 0 and ag == 0:
                p *= max(1 - mu_h * mu_a * rho, 0)
            elif hg == 1 and ag == 0:
                p *= max(1 + mu_a * rho, 0)
            elif hg == 0 and ag == 1:
                p *= max(1 + mu_h * rho, 0)
            elif hg == 1 and ag == 1:
                p *= max(1 - rho, 0)

            matrix[hg, ag] = p

    # Sum probabilities by outcome
    # np.tril(m, -1) = cells below the diagonal = home scores more = home win
    # np.diag(m)     = diagonal cells = equal scores = draw
    # np.triu(m,  1) = cells above the diagonal = away scores more = away win
    home_win_prob = float(np.sum(np.tril(matrix, -1)))
    draw_prob     = float(np.sum(np.diag(matrix)))
    away_win_prob = float(np.sum(np.triu(matrix, 1)))

    # Get all scorelines sorted by probability (most likely first)
    all_scores = [
        (matrix[hg, ag], hg, ag)
        for hg in range(MAX_GOALS)
        for ag in range(MAX_GOALS)
    ]
    all_scores.sort(reverse=True)

    # Most likely single scoreline
    top_prob, pred_h, pred_a = all_scores[0]

    return {
        "HomeTeam":       home,
        "AwayTeam":       away,
        "xG_Home":        round(mu_h, 2),
        "xG_Away":        round(mu_a, 2),
        "Pred_Home":      pred_h,
        "Pred_Away":      pred_a,
        "Pred_Prob":      round(top_prob * 100, 1),
        "Home_Win_Pct":   round(home_win_prob * 100, 1),
        "Draw_Pct":       round(draw_prob * 100, 1),
        "Away_Win_Pct":   round(away_win_prob * 100, 1),
        # Top 5 scorelines as a readable string e.g. "1-1(11%) 2-1(9%)"
        "Top_5_Scores":   "  ".join([
            str(h) + "-" + str(a) + "(" + str(round(p*100, 1)) + "%)"
            for p, h, a in all_scores[:5]
        ]),
    }


# --- OUTPUT FORMATTING -------------------------------------------------------

def print_predictions(predictions, title="Match Predictions"):
    """
    Prints a nicely formatted prediction table to the terminal.
    """
    print()
    print("  " + "=" * 72)
    print("  " + title)
    print("  " + "=" * 72)

    for pred in predictions:
        home = pred["HomeTeam"]
        away = pred["AwayTeam"]
        date_str = pred.get("Date", "")

        # Match header
        print()
        if date_str:
            print("  " + date_str + "  |  " + home + " vs " + away)
        else:
            print("  " + home + " vs " + away)

        print("  " + "-" * 60)

        # Predicted score
        print("  Predicted score:  " +
              home + " " + str(pred["Pred_Home"]) + " - " +
              str(pred["Pred_Away"]) + " " + away +
              "   (" + str(pred["Pred_Prob"]) + "% most likely)")

        # Expected goals
        print("  Expected goals:   " +
              str(pred["xG_Home"]) + " - " + str(pred["xG_Away"]))

        # Win/draw/loss bar
        hw = pred["Home_Win_Pct"]
        d  = pred["Draw_Pct"]
        aw = pred["Away_Win_Pct"]
        print("  Probabilities:    " +
              "Home " + str(hw) + "%   " +
              "Draw " + str(d)  + "%   " +
              "Away " + str(aw) + "%")

        # Top 5 scorelines
        print("  Top scorelines:   " + pred["Top_5_Scores"])

    print()
    print("  " + "=" * 72)


def save_predictions(predictions, filename):
    """
    Saves predictions to a CSV file in the outputs folder.
    """
    os.makedirs(OUTPUTS_FOLDER, exist_ok=True)
    df = pd.DataFrame(predictions)
    path = OUTPUTS_FOLDER + "/" + filename
    df.to_csv(path, index=False)
    print("  [OK] Saved: " + path)
    return path


# --- MODES -------------------------------------------------------------------

def run_specific_fixtures(lookup, params):
    """
    Mode 1: Predict the fixtures listed in the FIXTURES config above.
    """
    home_adv = params["home_advantage"]
    rho      = params["rho"]

    print("[Mode 1] Predicting " + str(len(FIXTURES)) + " specified fixtures...")

    predictions = []
    errors = []

    for fixture in FIXTURES:
        home = fixture[0]
        away = fixture[1]
        date_str = fixture[2] if len(fixture) > 2 else ""

        try:
            pred = predict_match(home, away, lookup, home_adv, rho)
            pred["Date"] = date_str
            predictions.append(pred)
        except ValueError as e:
            errors.append(str(e))

    if errors:
        print()
        print("  [WARN] Some fixtures could not be predicted:")
        for e in errors:
            print("    " + e)

    return predictions


def run_all_fixtures(lookup, params):
    """
    Mode 2: Predict every possible home/away combination for current teams.
    Useful for a full season forecast.
    """
    home_adv = params["home_advantage"]
    rho      = params["rho"]
    current  = params.get("current_teams", [])

    total = len(current) * (len(current) - 1)
    print("[Mode 2] Predicting all " + str(total) +
          " fixtures for current 20 teams...")

    predictions = []
    for home in sorted(current):
        for away in sorted(current):
            if home == away:
                continue
            pred = predict_match(home, away, lookup, home_adv, rho)
            pred["Date"] = ""
            predictions.append(pred)

    return predictions


# --- MAIN --------------------------------------------------------------------

def main():
    print("=" * 60)
    print("  EPL Score Predictor -- Script 04: Predict Matches")
    print("=" * 60)

    # Load ratings and model parameters
    print()
    print("[Step 1] Loading ratings and model parameters...")
    lookup, params = load_ratings_and_params()
    current_count = sum(1 for v in lookup.values() if v["Current"])
    print("  [OK] " + str(len(lookup)) + " teams loaded (" +
          str(current_count) + " current)")

    # Check which mode to run
    run_all = "--all" in sys.argv

    if run_all:
        # Mode 2: all fixtures
        predictions = run_all_fixtures(lookup, params)
        print_predictions(
            predictions[:10],
            title="All Fixtures -- First 10 Shown (see CSV for full list)"
        )
        filename = "predictions_all_fixtures.csv"
    else:
        # Mode 1: specific fixtures
        predictions = run_specific_fixtures(lookup, params)
        print_predictions(predictions, title="Gameweek Predictions")
        filename = "predictions_" + str(date.today()) + ".csv"

    # Save to CSV
    print("[Step 2] Saving predictions...")
    save_predictions(predictions, filename)

    print()
    print("=" * 60)
    print("  ALL DONE!")
    print("=" * 60)
    print()
    if not run_all:
        print("  To predict ALL possible fixtures, run:")
        print("  python3 src/04_predict_matches.py --all")
        print()
    print("  To predict different fixtures, edit the FIXTURES list")
    print("  at the top of this script.")
    print()


if __name__ == "__main__":
    main()
